# Generated by Django 3.2 on 2022-01-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked',
            name='number_of_guests',
            field=models.BooleanField(default=1, verbose_name=10),
            preserve_default=False,
        ),
    ]
