# Generated by Django 3.2 on 2022-01-13 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_booked_number_of_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Booked'), (2, 'NotBooked')], default=2),
        ),
        migrations.AlterField(
            model_name='booked',
            name='number_of_guests',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
