# Generated by Django 3.2 on 2022-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20220113_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='approved',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Booked'), (2, 'NotBooked')], default=0),
        ),
        migrations.AlterField(
            model_name='booked',
            name='number_of_guests',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6')], default=1),
        ),
    ]
