# Generated by Django 3.2 on 2022-03-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20220117_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booked',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
